### ISSUE TITLE
Yahoo API changed

### ISSUE THREAD

**Issue by sarunasb** [librehat/com.librehat.yahooweather#12]
Public calls to http://weather.yahooapis.com/forecastrss?w= are not working anymore, require OAuth1.

<yahoo:error xml:lang="en-US" yahoo:uri="http://yahoo.com">yahoo:descriptionPlease provide valid credentials. OAuth oauth_problem="OST_OAUTH_PARAMETER_ABSENT_ERROR", realm="yahooapis.com"/yahoo:descriptionyahoo:detailPlease provide valid credentials. OAuth oauth_problem="OST_OAUTH_PARAMETER_ABSENT_ERROR", realm="yahooapis.com"/yahoo:detail/yahoo:error

**Comment by librehat** [comment]
Thanks for reporting this. My hands are tied quite tightly recently. But I'll migrate the callback when I have free time.

**Comment by librehat** [comment]
Thanks for reporting this. My hands are tied quite tightly recently. But I'll migrate the callback when I have free time.

**Comment by smitgd** [comment]
Comment #9 of
http://stackoverflow.com/questions/36186538/making-yahoo-weather-api-request-with-oauth-1
says this fixes it:

If you simply replace
http://weather.yahooapis.com/
with
http://xml.weather.yahoo.com/
it should work ;)

Don't know why this works or if this is a robust solution but it does seems to fix the error after plasmoid is rebuilt and updated (and after a kde logout/in) with no addition of oauth stuff.
-gene

**Comment by smitgd** [comment]
librehat,
Didn't see that you had already fixed it in probably a better way. Sorry, just ignore my comment above. After rebuilding and updating using your new code, it also works fine.  Thanks!

**Comment by smitgd** [comment]
Installed the latest HEAD on two systems: fedora 23 and debian testing, both kde5. Noticed that "refresh" function would still actually fail with the original "check network" error message approximately 3 out of 4 tries. So I tried the change in the stackoverflow thread above again and it seems much more reliable. I haven't seen an error on either system after many refreshes using this fix (after checking out back to Sept 27 commit 4c1f9dbaebd2a893c5ccad7500ca4058995ea697 and applying the change suggested above).
-gene

**Comment by smitgd** [comment]
Hi librehat,
I installed the HEAD version marked 5.1.0 (Apr 3) on fedora 23 and debian testing. It works OK on fedora but fails on debian testing with this message printed in the box containing the plasmoid:

Error loading QML file: file:///home/gene/.local/share/plasma/plasmoids/com.librehat.yahooweather/contents/ui/main.qml:20:34: Type Weather unavailable
file:///home/gene/.local/share/plasma/plasmoids/com.librehat.yahooweather/contents/ui/Weather.qml:122:19: Type ForecastDelegate unavailable
file:///home/gene/.local/share/plasma/plasmoids/com.librehat.yahooweather/contents/ui/ForecastDelegate.qml:30:9: Cannot assign to non-existent property "usesPlasmaTheme"

(Before this, there was a message printed to install qml-models2 that I installed on debian.)

On fedora 23, I didn't install anything new since it worked right off. However, on fedora 23 when I do a manual "refresh" with the menu I see no progress indicator and this messages prints:
QMetaObject::invokeMethod: No such method QQuickItem_QML_32::actionTriggered(QVariant)
However, auto-update (when set e.g., to 1 minute) seems to work OK.
Any ideas?
Thanks,
-gene

**Comment by librehat** [comment]
Thanks for your testing
It seems Debian uses an older Plasma Desktop.

It is not related to API change. Could you open a new issue? Just copy and paste the description, thanks.

**Comment by librehat** [comment]
@smitgd I also updated `master` trunk, would you please check if it fixes your issues now?

**Comment by sarunasb** [comment]
Thanks you.

Version from master works fine on Kubuntu upgraded to 16.04 beta (needed to additionally install qml-module-qtqml-models2 package). 

On another computer with Kubuntu 15.10 the applet is continuously showing a spinning update circle. No error messages (or I don't know where to find them).

**Comment by smitgd** [comment]
Hi librehat,
On fedora 23 and debian testing today's master HEAD works except for 1 
issue.
When it first comes up after starting kde, the plasmoid contains the 
message "Unknown error." and the refresh button that I see you moved 
from the right-click menu (no weather data appears). After the refresh 
button is pressed one time the weather data appears and it seems to work 
after that.
-gene

**Comment by librehat** [comment]
@sarunasb you can use "plasmawindowed" to run it from command line. Error messages will be printed into terminal

**Comment by librehat** [comment]
@smitgd Just add onCompleted code back, please check `master` branch now.

**Comment by smitgd** [comment]
Hi Symeon,
I tried it but it still doesn't completely fix the problem, especially 
after a linux reboot. I no longer see the "Unknown error." message in 
the widget. Instead I see a continuous "spinning circle" progress 
indicator. But if I press the new "refresh" button the weather info 
comes up.

I think the reason for this is that the network/wi-fi is not yet up when 
the plasmoid first runs after a boot and it maybe times out attempting 
to get the data. But if the refresh button is pressed after the network 
is up, it tries again and works OK. I can see the same effect by 
disabling wi-fi and starting the plasmoid (using plasmawindowed). The 
spinning circle continues even after wi-fi is re-enabled until the 
refresh button is pressed (then the weather appears).

After a log-out/log-in to KDE, the weather info appears very shortly 
without the use of the refresh button. I assume this is because the 
network/wi-fi is already up before the plasmoid runs so no time-out occurs.

-gene

**Comment by sarunasb** [comment]
On 04/05/2016 02:57 PM, Symeon Huang wrote:

> @smitgd https://github.com/smitgd Just add onCompleted code back,
> please check |master| branch now.

Thank you! The plasmoid now works on both 15.10 and 16.04.

## 

Šarūnas Burdulis
http://math.dartmouth.edu/~sarunas

**Comment by librehat** [comment]
@smitgd I've fixed that in latest commit. :) Please test it and I'll roll out a bug fix update if everything is fine

**Comment by smitgd** [comment]
Now comes up OK after a reboot! Also tried it with plasmawindowed with network disabled and weather data came in after enabling wi-fi.
Noticed another formatting problem coming from yahoo. Sunrise time displays as "7:7 am" instead of "7:07 am". See this in the raw data accessed with curl. Of course, many units problems from yahoo are still present :(
